_: {
  home.sessionVariables = {
    NEXT_TELEMETRY_DISABLED = "1";
    NUXT_TELEMETRY_DISABLED = "1";
    CHECKPOINT_DISABLE = "1";
    DISABLE_TELEMETRY = "YES";
    ASTRO_TELEMETRY_DISABLED = "1";

    FNM_RESOLVE_ENGINES = "true";
    FNM_COREPACK_ENABLED = "true";
  };
}
